// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import "./globals.css"
// import type { Metadata } from "next"
// import Navbar from "@/components/Navbar"
// import Footer from "@/components/Footer"

// export const metadata: Metadata = {
//   title: "Hansanie Neththasinghe | Software Engineer",
//   description:
//     "Portfolio of Hansanie Neththasinghe - Software Engineering Undergraduate specializing in MERN, DevOps, and Cloud.",
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className="bg-slate-950 text-slate-200 min-h-screen flex flex-col">
//         <Navbar />
//         <main className="flex-1 container mx-auto px-6 py-12">
//           {children}
//         </main>
//         <Footer />
//       </body>
//     </html>
//   )
// }



"use client"

import "./globals.css"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import BackgroundBlobs from "@/components/BackgroundBlobs"
import { AnimatePresence, motion } from "framer-motion"
import { usePathname } from "next/navigation"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body className="bg-slate-950 text-slate-200 min-h-screen flex flex-col overflow-x-hidden">
        
        <BackgroundBlobs />

        <Navbar />

        <AnimatePresence mode="wait">
          <motion.main
            key={pathname}
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -30 }}
            transition={{ duration: 0.4 }}
            className="flex-1 container mx-auto px-6 py-12"
          >
            {children}
          </motion.main>
        </AnimatePresence>

        <Footer />
      </body>
    </html>
  )
}
